#!/usr/bin/python3.4
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
from gi.repository import GObject
sys.path.append('/usr/lib/lightbox')
from fvp_application import FvpApplication

GObject.threads_init()

fvpapp = FvpApplication()
ret = fvpapp.run(sys.argv)
sys.exit(ret)
